### PR TITLE
Delete random files and add .gitignore

### PR DESCRIPTION
**Pull request by jarhill0**

### CODE REVIEW

**Comment by frankdai320** [comment]
these migrations are useful, deleting them prevents them from being used

**Comment by jarhill0** [comment]
You're wrong. The migrations are here: https://github.com/frankdai320/music/tree/master/music_app/migrations

All I'm doing is deleting the crud like `__pycache__` that gathers but is unneccessary, and adding a .gitignore to prevent that in the future.

**Comment by jarhill0** [comment]
See how the extensions are `.pyc`? Yuck, don't want that in our cereal.

**Comment by frankdai320** [comment]
no u

**Comment by jarhill0** [comment]
ty homie

**Pull request merged**
